### 1. Login and Save Token
# We give this request a name, "@loginRequest"

POST http://localhost:8083/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "password123"
}

### 2. Validate the Token
GET http://localhost:8083/validate
# This is the magic. We tell it to use the token from the request named "@loginRequest"
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQHRlc3QuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc2MTQwMzIxMSwiZXhwIjoxNzYxNDM5MjExfQ.nZHKNKneM94JnfSPe-fWw7WoCC2iWEzp6_erXYk4AIWr_wU9FaxJuvZiZlzX4EeJe-B97pIt1D9UXNJUwfxadw